version: '3'

services:
  typescript-api-template:
    container_name: typescript-api-template-dev
    command: npm run debug
    environment:
      - NODE_ENV=development
    ports:
      - 9229:9229